name: new_adl
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - python=3.12.2
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit
  - _libgcc_mutex
  - _openmp_mutex
  - blas=1.0=mkl
  - brotli
  - bzip2
  - ca-certificates
  - certifi
  - charset-normalizer
  - cycler
  - cyrus-sasl
  - dbus
  - expat
  - ffmpeg
  - filelock
  - fontconfig
  - fonttools
  - freetype
  - glib
  - gmp
  - gnutls
  - gst-plugins-base
  - gstreamer
  - icu
  - idna
  - intel-openmp
  - jinja2
  - jpeg
  - kiwisolver
  - krb5
  - lame
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libclang
  - libedit
  - libffi
  - libgcc-ng
  - libglib
  - libgomp
  - libiconv
  - libidn2
  - libjpeg-turbo
  - libllvm14
  - libpng
  - libpq
  - libstdcxx-ng
  - libtasn1
  - libtiff
  - libunistring
  - libuuid
  - libwebp-base
  - libxcb
  - libxkbcommon
  - libxml2
  - llvm-openmp
  - lz4-c
  - markupsafe
  - matplotlib
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - mpmath
  - munkres
  - mysql
  - ncurses
  - nettle
  - networkx
  - numpy
  - openh264
  - openjpeg
  - openssl
  - packaging
  - pcre2
  - pillow
  - pip
  - ply
  - pyparsing
  - pyqt
  - pyqt5-sip
  - pysocks
  - python-dateutil
  - pyyaml
  - qt-main
  - readline
  - requests
  - setuptools
  - sip
  - six
  - sqlite
  - sympy
  - tbb
  - tk
  - tornado
  - typing_extensions
  - tzdata
  - urllib3
  - wheel
  - xz
  - yaml
  - zlib
  - zstd
